export default English = {
    "MEMBERS": "Members",
    "AIDS_FUNDS": "Aids fund",
    "SUBSCRIPION_TO_PARTICIPATE": "Subscription to participate",
    "NEED_TO_PARTICIPATE": "You need to pay a subsciption to participate",
    "SUBSCRIPION": "Subscription",
    "PARTICIPATE": "Participate",
    "NEXT_WIN": "NEXT WIN",
    "HOURS": "HOURS",
    "MINUTES": "MINUTES",
    "SECONDS": "SECONDS",
    "USER": "User",
    "HOME": "Home",
    "LOGIN": "Login",
    "LOGIN_SIGNUP": "Login/Signup",
    "CHECKOUT": "Checkout",
    "CARD_NUMBER": "Card Number",
    "CARD_HOLDER": "Card Holder",
    "EXPIRES": "Expires",
    "RE_PASSWORD": "Re-Password",
    "PASSWORD_ERROR": "Password does'nt match",
    "ADD_CARD": "Add Card",
    "EXPIRY_MONTH": "Expiry Month",
    "EXPIRY_YEAR": "Expiry Year",
    "EXPIRY_DATE": "Expiry Date",
    "SIGN_UP": "Signup",
    "SIGN_IN": "Sign in",
    "PASSWORD": "Password",
    "THANKS_FOR_ORDER": "Thanks for order!",
    "THANKS_FOR_ORDER_TEXT": "You are now able to participate everyday to GIMONII project",
    "DELETE_ACCOUNT": "Delete Account",
    "PAY_SUBCIPTION": "Pay Subcription 4 €/Month",
    "NOTIFICATIONS": "Notfications",
    "ABOUT": "About",
    "AFFILIATIONS": "Affiliations",
    "WINNERS": "Winners",
    "NEW_PASSWROD": "New Password",
    "CONFIRM_NEW_PASSWROD": "Confirm New Password",
    "CURRENT_PASSWROD": "Current Password",
    "UPDATE_NEW_PASSWROD": "Update new password",
    "SETTINGS": "Settings",
    "FORGOT_PASSWORD": "Forgot Password ?",
    "NEXT": "Next",
    "AFFILIATION_ERROR": "Affiliation code already exists",
    "FORGOT_MESSAGE": "Enter your email and we’ll send to you the link to reset the password",
    "VERIFY": "Verify",
    "SEARCH": "Search",
    "ALERT": "Alert",
    "ERROR": "Error",
    "EMAIL_ERROR": "The email adress is badly formatted",
    "FIRST_NAME": "First Name",
    "START_GIMONII": "Start Gimonii",
    "ADDITIONAL_SETTINGS": "Additional Settings",
    "LOGOUT": "Logout",
    "PERSONAL_INFORMATION": "Personal information",
    "AFFILIATION_CODE": "Affiliation code",
    "AFFILIATION_CODE_TEXT": "We need you to add affiliation code of your friend or an influencer. So we can enter on gimonii",
    "LOCATION": "Location",
    "SUBMIT": "Submit",
    "ABOUT_TEXT": "1.Gimonii is an app that offers gifts, makes you money and donates to many associations and people need help all over the world \n\n2.Register, get your personal code and communicate it around you. Each person using your code to register, give you back 1€ as well as 1€ has a fund of help that redistributes to associations.\n\n3.With gimonii, you can easily help others, have chance to get lucky present everyday and make money. \n\nThanks to you!",
    "CHANGE": "Change",
    "ACCOUNT_DELETE": "Account delete",
    "CANCEL": "Cancel",
    "OK": "Ok",
    "ACCOUNT_DELETE_TEXT": "Are you sure you want to delete your account?",
    "COUNTRY": "Country",
    "SHARE": "Share",
    "CARD": "Card",
    "PASSWROD": "Password",
    "PROFILE": "Profile",
    "NUMBER_AFFILIATE": "Number affiliate",
    "AFFILIATE_MEMBERS": "Affiliate members",
    "MODAL_CLOSED": "Modal has been closed.",
    "CREATE_ACCOUNT": "Create account",
    "UPDATE_NEW_LOCATION": "Update new location",
    "LOCATION_TEXT": "You must enter location",
    "AGREED": "I agree",
    "INVALID_EMAIL": "Invalid email",
    "INVALID_YEAR": "Invalid year",
    "INVALID_MONTH": "Invalid month",
    "POLICY": "I agree to gimonii payment policy, cancellation policy and terms of use",
    "FRENCH":"French",
    "PASSWORD_CHANGED": "Password Changed",
    "ERROR_CODE_USER_NOT_FOUND": "Error: There is no user record corresponding to this identifier. The user may have been deleted.",
    "ERROR_MSG_WRONG_PASSWORD": "Your password in incorrect !",
    "EMAIL_SENT": "Email Sent! check your email.",
    "ERROR_MSG_ALREADY_USED_EMAIL": "The email address is already in use by another account.",
    "ERROR_MISSING_CARD_NUMBER": "Error: Missing required param: card number.",
    "ERROR_MISSING_NAME": "Cannot read property 'firstName' of null",
    "ERROR_EXPIRE_YEAR": "Error: Your card's expiration year is invalid.",
    "ERROR_EMPTY_FIELD": "Empty Fields",
    "ERROR_TEST_CARD": "Error: Your card was declined. Your request was in live mode, but used a known test card.",
    "ERROR_LONG_PASS": "Error: The password must be 6 characters long or more.",
    "ERROR_SHOULD_LONG_PASS": "Error: password should be at least 6 characters",
    "ERROR_SENSITIVE_PASS": "Error: This operation is sensitive and requires recent authentication. Log in again before retrying this request.",
    "ERROR_CODE_503":"Error: Request failed with status code 503",
    "ERROR_NOT_FIND_PAYMENT":"Error: Could not find payment information",
    "ERROR_NUMBER_INVALID":"Error: Your card's number is invalid.",
    "ERROR_NUMBER_INCORRECT":"Error: Your card number is incorrect.",
    "ERROR_NUMBER_NOT_VALID":"Error: The card number is not a valid credit card number.",
    "YOUR_AFFILIATION_CODE": "Create your own affiliation code",
    "AFFILIATION_ERROR_LENGTH": "Affiliation code must be 4 digits",
    "AFFILIATE_TO": "Affiliate to",
    "PERSONAL_CODE": "Personal code",
    "SOMETHING_WENT_WRONG": "Something went wrong",
    "Password_at_least_6_characters":"Password at least 6 characters"

}