export default French = {
    "MEMBERS": "Membres",
    "AIDS_FUNDS": "Fond d’aide",
    "SUBSCRIPION_TO_PARTICIPATE": "Abonnement pour participer",
    "SUBSCRIPION": "Abonnement",
    "NUMBER_AFFILIATE": "Numéro d'Affilié",
    "PROFILE": "Compte",
    "NEED_TO_PARTICIPATE": "Vous devez payer un abonnement pour participer",
    "PARTICIPATE": "Participer",
    "NEXT_WIN": "Prochain tirage",
    "HOURS": "Heures",
    "MINUTES": "Minutes",
    "SECONDS": "Secondes",
    "USER": "Utilisateur",
    "EXPIRY_DATE": "Date d'Expiration",
    "ADD_CARD": "Ajouter une carte",
    "EXPIRY_YEAR": "Année D'expiration",
    "EXPIRY_MONTH": "Mois D'expiration",
    "EXPIRES": "Expire",
    "CARD_HOLDER": "Titulaire de la carte",
    "CARD_NUMBER": "Numéro de carte",
    "AFFILIATION_CODE_TEXT": "Nous avons besoin de vous pour ajouter le code d'affiliation de votre ami ou d'un influenceur. Pour que nous puissions entrer sur Gimonii",
    "CHECKOUT": "Check-out",
    "LOGIN_SIGNUP": "Se connecter/S'inscrire",
    "SUBMIT": "Soumettre",
    "ABOUT_TEXT": `1. Gimonii est une application qui vous fait gagner des cadeaux, vous rapporte de l’argent et fait des dons à de nombreuses associations ainsi que des personnes dans le besoin à travers le monde.
    \n2. Inscrivez-vous, obtenez votre code personnel et communiquez-le autour de vous. Chaque personne utilisant votre code pour s’inscrire vous reverse 1€ ainsi qu’1€ à un fond d’aide qui redistribue l’argent à des associations.
    \n3. Avec Gimonii, vous pouvez facilement aider les autres, avoir la chance de remporter des cadeaux tous les jours et de gagner de l’argent.
    \nMerci à toi`,
    "ACCOUNT_DELETE": "Compte supprimer",
    "HOME": "Accueil",
    "LOGIN": "S’Identifier",
    "SIGN_UP": "S’Inscrire",
    "SIGN_IN": "Se Connecter",
    "NOTIFICATIONS": "Notfications",
    "ACCOUNT_DELETE_TEXT": "Êtes-vous sûr de vouloir supprimer votre compte?",
    "SHARE": "Partager",
    "PASSWORD_ERROR": "Le mot de passe ne correspond pas",
    "MODAL_CLOSED": "Modal a été fermé.",
    "CREATE_ACCOUNT": "Créer un compte",
    "PASSWORD": "Mot de passe",
    "AFFILIATION_ERROR": "Le code d'affiliation existe déjà",
    "RE_PASSWORD": "Re-mot de passe",
    "SEARCH": "Chercher",
    "FORGOT_PASSWORD": "Mot de passe oublié ?",
    "NEXT": "Continuer",
    "FORGOT_MESSAGE": "Entrez votre e-mail et recevez le lien pour réinitialiser votre mot de passe",
    "VERIFY": "Vérifier",
    "ALERT": "Alerte",
    "ERROR": "Erreur",
    "EMAIL_ERROR": " L’adresse e-mail ne correspond pas",
    "FIRST_NAME": "Prénom",
    "LOGOUT": "déconnexion",
    "AFFILIATION_CODE": "Code d’Affiliation ",
    "YOUR_AFFILIATION_CODE": "Créez votre propre code d'affiliation",
    "LOCATION": "Ville",
    "LOCATION_TEXT": "Vous devez entrer lieu",
    "AFFILIATION_ERROR_LENGTH": "Le code d'affiliation doit comporter 4 chiffres",
    "AFFILIATE_MEMBERS": "Membres affiliés",
    "PAY_SUBCIPTION": "Abonnement payant 4 € / mois",
    "DELETE_ACCOUNT": "Supprimer le compte",
    "ABOUT": "Merci a vous",
    "PERSONAL_INFORMATION": "Informations personnelles",
    "ADDITIONAL_SETTINGS": "Paramètres additionnels",
    "WINNERS": "Gagnants",
    "SETTINGS": "Réglages",
    "THANKS_FOR_ORDER_TEXT": "Vous êtes capable se participer chaque jour au projet GIMONII",
    "START_GIMONII": "Démarrer gimonii",
    "THANKS_FOR_ORDER": "Merci pour la commande!",
    "OK": "D'Accord",
    "CANCEL": "Annuler",
    "CARD": "Carte",
    "AFFILIATIONS": "Les affiliations",
    "CHANGE": "Changement",
    "COUNTRY": "Pays",
    "PASSWROD": "Mot de passe",
    "CURRENT_PASSWROD": "Mot de passe actuel",
    "NEW_PASSWROD": "Nouveau mot de passe",
    "CONFIRM_NEW_PASSWROD": "Confirmer le nouveau mot de passe",
    "INVALID_EMAIL": "Email invalide",
    "AGREED": "Je suis d'accord",
    "INVALID_YEAR": "Année invalide",
    "INVALID_MONTH": "Mois invalide",
    "UPDATE_NEW_PASSWROD": "Mettre à jour le nouveau mot de passe",
    "UPDATE_NEW_LOCATION": "Mettre à jour un nouvel emplacement",
    "POLICY": "J'accepte les conditions de paiement, les conditions d'annulation et les conditions d'utilisation De gimonii",
    "FRENCH": "Français",
    "PASSWORD_CHANGED": "Mot De Passe Changé",
    "ERROR_CODE_USER_NOT_FOUND": "Erreur: Il n'y a pas d'enregistrement d'utilisateur correspondant à cet identifiant. L'utilisateur peut avoir été supprimé.",
    "ERROR_MSG_WRONG_PASSWORD": "Votre mot de passe est incorrect!",
    "EMAIL_SENT": "Email envoyé! vérifier votre email.",
    "ERROR_MSG_ALREADY_USED_EMAIL": "L'adresse email est déjà utilisée par un autre compte",
    "ERROR_MISSING_CARD_NUMBER": "Erreur: Paramètre requis manquant: carte [numéro].",
    "ERROR_EXPIRE_YEAR": "Erreur: L'année d'expiration de votre carte est invalide.",
    "ERROR_MISSING_NAME": "Impossible de lire la propriété 'firstName' de null",
    "ERROR_TEST_CARD": "Erreur: votre carte a été refusée. Votre demande était en mode direct, mais utilisait une carte de test connue.",
    "ERROR_EMPTY_FIELD": "Champs Vides",
    "ERROR_LONG_PASS": "Erreur: le mot de passe doit comporter 6 caractères ou plus.",
    "ERROR_SHOULD_LONG_PASS": "Erreur: le mot de passe doit comporter au moins 6 caractères",
    "ERROR_SENSITIVE_PASS": "Erreur: Cette opération est sensible et nécessite une authentification récente. Connectez-vous à nouveau avant de réessayer cette demande.",
    "ERROR_CODE_503":"Erreur: la requête a échoué avec le code d'état 503",
    "ERROR_NUMBER_INVALID":"Erreur: Le numéro de votre carte est invalide.",
    "ERROR_NOT_FIND_PAYMENT":"Erreur: Impossible de trouver les informations de paiement",
    "ERROR_NUMBER_NOT_VALID":"Erreur: le numéro de carte n'est pas un numéro de carte de crédit valide.",
    "ERROR_NUMBER_INCORRECT":"Erreur: Votre numéro de carte est incorrect.",
    "AFFILIATE_TO": "Affilié à",
    "PERSONAL_CODE": "Code personnel",
    "SOMETHING_WENT_WRONG": "Quelque chose a mal tourné",
    "Password_at_least_6_characters":"Mot de passe au moins 6 caractères"
}